const myProjects = [
  {
    id: 1,
    title: "SRE Incident Mgmt Tool",
    desc: "Automate incident response, reduce downtime and enhance your tech team's delivery with Squadcast’s Reliability Automation Platform. Bring together all your on-call and incident response workflows under one unified platform.",
    image: "squadcast",
    link: "https://www.squadcast.com/",
    iframeLink:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.0860354259257!2d77.67369087583351!3d12.902189116394798!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1391f1666ee1%3A0x71ecc7aeac157b1f!2sSquadcast%20Labs%20Private%20limited!5e0!3m2!1sen!2snp!4v1713931764610!5m2!1sen!2snp",
    tech: [
      "TypeScript",
      "Chakra UI",
      "RTL",
      "Zustand",
      "React Hook Form",
      "React Query",
      "GraphQl",
      "Zod",
      "Lodash",
      "React Error Boundary",
      "Unleash Proxy Client",
    ],
    myContribution: [
      "Squadcast is a product based end-to-end Incident management software based on US and India, helping SRE,DevOps and engineers do on-call scheduling and incident management in the SRE way.",
      "2 weeks scrum plan where I get tickets on Jira board for building, alerting and on-call management feature intuitive",
      "Active oncall handover,meetings,standup with PM about feature . ",
      "Common practise with Chakra-UI,sq own library,Ts,luxon,react hookform,react query,graphql to develop a feature for dashboard based project. ",
    ],
  },
  {
    id: 2,
    title: "Loan Mgmt Tool",
    desc: "It is a dashboard Fin-tech product of MIFIN focused for loan retrieving from clients",
    image: "qualtech",
    link: "https://www.qualtechedge.com/",
    iframeLink:
      "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14010.277467094395!2d77.387651!3d28.612693!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cef8db73daae9%3A0x70c6f82448bac7a1!2sQualtech!5e0!3m2!1sen!2sin!4v1713933805514!5m2!1sen!2sin",
    tech: [
      "Vite",
      "TypeScript",
      "Chakra UI",
      "Zustand",
      "@tanstack",
      "React Hook Form",
      "React Query",
      "Zod",
      "React Error Boundary",
    ],
    myContribution: [
      "Qualtech is a Fin-tech product of MIFIN based on India, focused for loan retrieving from clients.",
      "Started project from scratch where tech like vite, react18,typescript, @tanstack, react-query ,zustand,react-hook-form ,Chakra was used.",
      "Made reusable components for across the project under strict code review environment.",
      "Worked as maintainer for PR reviews and quality code",
    ],
  },
  {
    id: 3,
    title: "Trainee Mgmt System",
    desc: "Web based dashboard system to manage, train ,schedule, exam, quiz resource, video learning platform  for government officers",
    image: "sikai",
    link: "https://www.nasc.org.np/",
    iframeLink:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3533.491755190028!2d85.31073757609201!3d27.671192227084042!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb1832b2c9a291%3A0x91894fa7594334d9!2sNepal%20Administrative%20Staff%20College!5e0!3m2!1sen!2sin!4v1713935587066!5m2!1sen!2sin",
    tech: [
      "TypeScript",
      "Chakra UI",
      "Redux Toolkit",
      "@tanstack",
      "Formik",
      "React Query",
      "YUP",
      "JWT",
    ],
    myContribution: [
      "Developed a Trainee Management System for government sector edu wing using TypeScript, ReactQuery, JWT, rtk and Chakra UI.",
      "Implemented user authentication and authorization using JWT,worked in roles and permission of user for CRUD access",
      "Created trainee profiles using Chakra UI for a visually appealing interface.",
      "Utilized React Query for efficient data fetching and caching.",
      "Designed a tracking system for training programs and progress monitoring.",
      "Implemented Generating reports feature for trainee progress and performance.",
    ],
  },
  {
    id: 4,
    title: "Doctor Appointment System",
    desc: "Web based doctor appointment booking system including web video call and payment system",
    image: "nepmeds",
    link: "https://www.nepmeds.com.np/",
    iframeLink:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7063.879961094374!2d85.34027849568015!3d27.719139352303667!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb1b26096329eb%3A0x6a0e927a9e1f4bdc!2sNepmeds%20Pvt.ltd!5e0!3m2!1sen!2snp!4v1713935839670!5m2!1sen!2snp",
    tech: [
      "TypeScript",
      "Chakra UI",
      "reactchart2js",
      "React Context",
      "@tanstack",
      "react Hook Form",
      "React Query",
      "YUP",
      "JWT",
    ],
    myContribution: [
      "Developed a doctor appointment system using TypeScript, ReactQuery, JWT , zustand , reactchart2js and Chakra UI.",
      "Implemented user authentication and authorization using JWT,worked in roles and permission of user for CRUD access",
      "Developed doctor booking according to their schedule with integrated khalti and esewa payment",
      "Utilized React Query for efficient data fetching and caching.",
      "Regular PR reviews practise.",
    ],
  },
  {
    id: 5,
    title: "Dharti Agro",
    desc: "Website for indian client built using nextJS, shadcn ui and tailwind, reflecting their moto and campaign",
    image: "dharti",
    link: "https://gitlab.com/Prawesh11/dharti_website",
    tech: [
      "NextJS",
      "TypeScript",
      "Shadcn UI",
      "Tailwind Css",
      "Framer Motion",
    ],
    myContribution: [
      "Developed a website from scratch using NextJs, TypeScript, Shadcn UI with unique animation using framer motion",
    ],
  },
  {
    id: 6,
    title: "Moru blog page",
    desc: "Moru is a fintech digital wallet company whose blog website was built using antD,redux-toolkit and vite",
    image: "moru",
    link: "https://github.com/AsheshRanaGurung/MoruBlog",
    iframeLink:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.1738130400213!2d85.325773976093!3d27.71191922528871!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb199a12d7497d%3A0xda6c2c0bbb0658ba!2sPay%20Nep%20Pvt%20Ltd!5e0!3m2!1sen!2snp!4v1713937426927!5m2!1sen!2snp",
    tech: [
      "React JS",
      "Ant Design",
      "React helmet",
      "mdb-react-ui-kit",
      "React Share",
      "Formik",
      "Redux Toolkit",
      "Animate on Scroll",
      "JWT",
    ],
    myContribution: [
      "Developed a blogging website with admin Panel and RBAC feature from scratch using ReactJs, ant Design ,JWT and AOS",
      "Added comment features on blog with sharing blog feature using react share",
      "Added SEO metaData using react helmet",
      "Parsed the html dtaa blog to UI using mdb react"
    ],
  },
  {
    id: 7,
    title: "3D websites",
    desc: "Built a website using ThreeJS and tailwind with interactive UI and working socials including emailJS",
    image: "web",
    link: "https://github.com/AsheshRanaGurung/3dPortfolio",
  tech: [
      "React JS",
      "React three/drei",
      "React three/fiber",
      "Three Js",
      "React Confetti",
      "React Share",
      "Animate on Scroll",
      "Tailwind",
    ],
    myContribution: [
    "All this that you are seeing in this website was done by me, so yeah, that's all"
    ],
  },
  {
    id: 8,
    title: "Babaal Ecommerce ",
    desc: "A full stack project I did long back for uni project with react as FE and django as BE with sqlite as DB",
    image: "dummy",
    link: "https://github.com/AsheshRanaGurung/BabaalDeal",
    tech: [
      "React Js",
      "Django",
      "Sqlite/ Postgres",
      "Axios",
      "Mdbreact",
      "React Bootstrap",
      "Redux",
      "React Router Dom",
      ],
      myContribution: [
      "This was a project back in 2021 so I forgot most of the highlight, but you can check the code in the github link."
      ],
  },
  {
    id: 9,
    title: "Random Project ",
    desc: "A project I did long back but lost its code and docs",
    image: "dummy",
  },
];
export default myProjects;
